server:
  port: 8090
spring:
  application:
    name: config
  cloud:
    consul:
      host: 192.168.99.103
      port: 8500
    config:
      server:
        git:
          uri: http://192.168.99.108/sc-projects/sc-config-repository.git
          basedir: ./basedir
    bus:
      ack:
        enabled: true
  rabbitmq:
    host: 192.168.99.108
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh