server:
  port: 8090
spring:
  application:
    name: config
  cloud:
    consul:
      host: 192.168.99.103
      port: 8500
    config:
      server:
        git:
          uri: https://github.com/dlamon/sc-config-repository.git
          basedir: ./sc-config/basedir
    bus:
      ack:
        enabled: true
  rabbitmq:
    host: 192.168.99.108
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "bus-refresh"]
logging:
  graylog:
    host: 192.168.99.108
    port: 12201